# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine

WORKDIR /app

# Copy project files
COPY package.json bun.lockb* ./
COPY *.ts ./
COPY tsconfig.json ./
COPY README.md ./

# Install dependencies
RUN bun install

# Start the MCP server
CMD ["bun", "run", "index.ts"]
